#!/bin/bash
if [[ $SERVICE_DEBUG_MODE == "true" ]]; then
  export FLASK_RUN_PORT=9000
  export FLASK_APP=server
  export FLASK_ENV=development;
  export FLASK_DEBUG=1;
  exec flask run --host=0.0.0.0
else
  exec gunicorn -w 4 -b 0.0.0.0:9000 'server:app'
fi
